spring.application.name=redis
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/dbRedis
spring.datasource.password=thanghuy
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# Redis Cluster (3 master + 3 replica)

spring.data.redis.cluster.nodes=localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005,localhost:7006
spring.data.redis.cluster.max-redirects=3
spring.cache.type=redis
logging.level.org.springframework.cache=DEBUG
# JWT - key 64 bytes (512-bit) chuan Base64
jwt.secret=dGhpcz1pcy1hLTI1Ni1iaXQtc2VjcmV0LWtleS1mb3ItbmVnQWtoeS1sdWNreS1zcGluLWFwcC1zZWNyZXQ=
jwt.expiration=86400000